servers/urls.py
from django.conf.urls import url
from django.contrib import admin
from monitoring import views

urlpatterns = [
    url(r'^$', views.logins, name='index'),
]

monitoring/models.py
from django.db import models
import json


class User(models.Model):
    username = models.CharField(max_length=32, unique=True, db_index=True)
    full_name = models.CharField(max_length=128)
    _contact = models.CharField(max_length=4096, db_column="contact", default="[]")

    @property
    def contact(self):
        return tuple(json.loads(self._contact or '[]'))

    @contact.setter
    def contact(self, contact):
        self._contact = json.dumps(list(set(contact)))

class Server(models.Model):
    name = models.CharField(max_length=32, unique=True, blank=True, null=True)
    ip_address = models.GenericIPAddressField(unique=True, db_index=True)
    current_users = models.ManyToManyField(User, through="Session")

class Session(models.Model):
    login_time = models.DateTimeField()
    login_time_full = models.BooleanField(default=True)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        index_together = [
            ('server', 'user'),
        ]

monitoring/views.py
from django.shortcuts import render
from .models import Server


def logins(request):
    servers = Server.objects.order_by("name")
    return render(request, "../templates/logins.html", {'servers': servers})

monitoring/templates/logins.html
<table>
    <tr>
        <th>Name</th>
        <th>IP</th>
        <th>Username</th>
        <th>Full Name</th>
        <th>Login Time</th>
        <th>Contact</th>
    </tr>
    {% for server in servers %}
    <tr>
        <td>{{server.name}}</td>
        <td>{{server.ip_address}} </td>
        {% for user in server.current_users.all %}
            {% for session in user.session_set.all %}
                {% if server == session.server %}
                    <tr>
                        <td colspan=2></td>
                        <td>{{user.username}}</td>
                        <td>{{user.full_name}}</td>
                        <td>
                            {% if session.login_time_full %}
                                {{session.login_time|date:"Y-m-d H:i:s"}}
                            {% else %}
                                {{session.login_time|date:"Y-m-d"}}
                            {% endif %}
                        </td>
                        <td>{{user.contact|join:", "}}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
        <tr><td>&nbsp;</td></tr>
    </tr>
    {% endfor %}
<table>